matlab -nodisplay -r "gpTensorImpValidation(1,2000,'mimicConfig')" 2>&1 > /home/shared_data/mimic3/gpml/log/imp1.log&
matlab -nodisplay -r "gpTensorImpValidation(2,2000,'mimicConfig')" 2>&1 > /home/shared_data/mimic3/gpml/log/imp2.log&
matlab -nodisplay -r "gpTensorImpValidation(3,2000,'mimicConfig')" 2>&1 > /home/shared_data/mimic3/gpml/log/imp3.log&
matlab -nodisplay -r "gpTensorImpValidation(4,2000,'mimicConfig')" 2>&1 > /home/shared_data/mimic3/gpml/log/imp4.log&
matlab -nodisplay -r "gpTensorImpValidation(5,2000,'mimicConfig')" 2>&1 > /home/shared_data/mimic3/gpml/log/imp5.log&
matlab -nodisplay -r "gpTensorImpValidation(6,2000,'mimicConfig')" 2>&1 > /home/shared_data/mimic3/gpml/log/imp6.log&
matlab -nodisplay -r "gpTensorImpValidation(7,2000,'mimicConfig')" 2>&1 > /home/shared_data/mimic3/gpml/log/imp7.log&
matlab -nodisplay -r "gpTensorImpValidation(8,2000,'mimicConfig')" 2>&1 > /home/shared_data/mimic3/gpml/log/imp8.log&
matlab -nodisplay -r "gpTensorImpValidation(9,2000,'mimicConfig')" 2>&1 > /home/shared_data/mimic3/gpml/log/imp9.log&
matlab -nodisplay -r "gpTensorImpValidation(10,2000,'mimicConfig')" 2>&1 > /home/shared_data/mimic3/gpml/log/imp10.log&
matlab -nodisplay -r "gpTensorImpValidation(11,2000,'mimicConfig')" 2>&1 > /home/shared_data/mimic3/gpml/log/imp11.log&
matlab -nodisplay -r "gpTensorImpValidation(12,2000,'mimicConfig')" 2>&1 > /home/shared_data/mimic3/gpml/log/imp12.log&
matlab -nodisplay -r "gpTensorImpValidation(13,2000,'mimicConfig')" 2>&1 > /home/shared_data/mimic3/gpml/log/imp13.log&
matlab -nodisplay -r "gpTensorImpValidation(14,2000,'mimicConfig')" 2>&1 > /home/shared_data/mimic3/gpml/log/imp14.log&
matlab -nodisplay -r "gpTensorImpValidation(15,2000,'mimicConfig')" 2>&1 > /home/shared_data/mimic3/gpml/log/imp15.log&
matlab -nodisplay -r "gpTensorImpValidation(16,2000,'mimicConfig')" 2>&1 > /home/shared_data/mimic3/gpml/log/imp16.log&
matlab -nodisplay -r "gpTensorImpValidation(17,2000,'mimicConfig')" 2>&1 > /home/shared_data/mimic3/gpml/log/imp17.log&
matlab -nodisplay -r "gpTensorImpValidation(18,2000,'mimicConfig')" 2>&1 > /home/shared_data/mimic3/gpml/log/imp18.log&
matlab -nodisplay -r "gpTensorImpValidation(19,2000,'mimicConfig')" 2>&1 > /home/shared_data/mimic3/gpml/log/imp19.log&
matlab -nodisplay -r "gpTensorImpValidation(20,2000,'mimicConfig')" 2>&1 > /home/shared_data/mimic3/gpml/log/imp20.log&
matlab -nodisplay -r "gpTensorImpValidation(21,2000,'mimicConfig')" 2>&1 > /home/shared_data/mimic3/gpml/log/imp21.log&
matlab -nodisplay -r "gpTensorImpValidation(22,2000,'mimicConfig')" 2>&1 > /home/shared_data/mimic3/gpml/log/imp22.log&
matlab -nodisplay -r "gpTensorImpValidation(23,2000,'mimicConfig')" 2>&1 > /home/shared_data/mimic3/gpml/log/imp23.log&
matlab -nodisplay -r "gpTensorImpValidation(24,2000,'mimicConfig')" 2>&1 > /home/shared_data/mimic3/gpml/log/imp24.log&
matlab -nodisplay -r "gpTensorImpValidation(25,2000,'mimicConfig')" 2>&1 > /home/shared_data/mimic3/gpml/log/imp25.log&
matlab -nodisplay -r "gpTensorImpValidation(26,2000,'mimicConfig')" 2>&1 > /home/shared_data/mimic3/gpml/log/imp26.log&
